# Use the official PostgreSQL image as the base image
FROM postgres:latest

# Set the environment variables for the database
ENV POSTGRES_USER user
ENV POSTGRES_PASSWORD password
ENV POSTGRES_DB gin-boilerplate
